// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package webhookdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Client struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Email          string             `json:"email"`
	RequestType    string             `json:"request_type"`
	PatrimonyValue pgtype.Numeric     `json:"patrimony_value"`
	Status         string             `json:"status"`
	Priority       pgtype.Text        `json:"priority"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type WebhookEvent struct {
	EventID     string             `json:"event_id"`
	CardID      string             `json:"card_id"`
	ClientEmail string             `json:"client_email"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
}
