// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook_event.sql

package webhookdb

import (
	"context"
)

const getWebhookEventByID = `-- name: GetWebhookEventByID :one
SELECT event_id, card_id, client_email, processed_at FROM webhook_events WHERE event_id = $1
`

func (q *Queries) GetWebhookEventByID(ctx context.Context, eventID string) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, getWebhookEventByID, eventID)
	var i WebhookEvent
	err := row.Scan(
		&i.EventID,
		&i.CardID,
		&i.ClientEmail,
		&i.ProcessedAt,
	)
	return i, err
}

const insertWebhookEvent = `-- name: InsertWebhookEvent :one
INSERT INTO webhook_events (event_id, card_id, client_email)
VALUES ($1, $2, $3)
RETURNING event_id, card_id, client_email, processed_at
`

type InsertWebhookEventParams struct {
	EventID     string `json:"event_id"`
	CardID      string `json:"card_id"`
	ClientEmail string `json:"client_email"`
}

func (q *Queries) InsertWebhookEvent(ctx context.Context, arg InsertWebhookEventParams) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, insertWebhookEvent, arg.EventID, arg.CardID, arg.ClientEmail)
	var i WebhookEvent
	err := row.Scan(
		&i.EventID,
		&i.CardID,
		&i.ClientEmail,
		&i.ProcessedAt,
	)
	return i, err
}
