// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: client.sql

package clientdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClient = `-- name: CreateClient :one
INSERT INTO clients (name, email, request_type, patrimony_value)
VALUES ($1, $2, $3, $4)
RETURNING id, name, email, request_type, patrimony_value, status, priority, created_at, updated_at
`

type CreateClientParams struct {
	Name           string  `json:"name"`
	Email          string  `json:"email"`
	RequestType    string  `json:"request_type"`
	PatrimonyValue float64 `json:"patrimony_value"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, createClient,
		arg.Name,
		arg.Email,
		arg.RequestType,
		arg.PatrimonyValue,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.RequestType,
		&i.PatrimonyValue,
		&i.Status,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClientByEmail = `-- name: GetClientByEmail :one
SELECT id, name, email, request_type, patrimony_value, status, priority, created_at, updated_at FROM clients WHERE email = $1
`

func (q *Queries) GetClientByEmail(ctx context.Context, email string) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByEmail, email)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.RequestType,
		&i.PatrimonyValue,
		&i.Status,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateClientStatusAndPriority = `-- name: UpdateClientStatusAndPriority :one
UPDATE clients
SET status = $1, priority = $2, updated_at = NOW()
WHERE email = $3
RETURNING id, name, email, request_type, patrimony_value, status, priority, created_at, updated_at
`

type UpdateClientStatusAndPriorityParams struct {
	Status   string      `json:"status"`
	Priority pgtype.Text `json:"priority"`
	Email    string      `json:"email"`
}

func (q *Queries) UpdateClientStatusAndPriority(ctx context.Context, arg UpdateClientStatusAndPriorityParams) (Client, error) {
	row := q.db.QueryRow(ctx, updateClientStatusAndPriority, arg.Status, arg.Priority, arg.Email)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.RequestType,
		&i.PatrimonyValue,
		&i.Status,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
